--CAN BE USED TO SEND PLAIN TEXT, JSON OR WHATEVER.  
--IT DIRECTS THE RECIEVER IT HAS A PAYLOAD BUT NOTHING TO VALIDATE
CREATE MESSAGE TYPE [ReceiverMessageType]
	VALIDATION = NONE
GO

CREATE MESSAGE TYPE [ValidatedReceiverMessageType]
	VALIDATION = VALID_XML WITH SCHEMA COLLECTION [ValidatedData]
GO

CREATE MESSAGE TYPE [ErrorReceiverMessageType]
    VALIDATION = VALID_XML WITH SCHEMA COLLECTION [ErrorData]
GO

--IN THIS CONTEXT WE ARE USING EMPTY MESSAGES AS SUCCESS, LIKE 200 OK in WebApis
CREATE MESSAGE TYPE [EmptyReceiverMessageType]
	VALIDATION = EMPTY
GO

--THIS MERELY AN EXAMPLE OF XML BUT NOT VALIDATED, USED TO MAKE SURE THE WIRE DIDN'T CORRUPT THE MESSAGE
--IT ISN'T USED IN THE EXAMPLE PROJECT
CREATE MESSAGE TYPE [WellFormedXMLReceiverMessageType]
	VALIDATION = WELL_FORMED_XML
GO


