CREATE MESSAGE TYPE [SenderMessageType]
	VALIDATION = NONE
GO

CREATE MESSAGE TYPE [ValidatedSenderMessageType]
	VALIDATION = VALID_XML WITH SCHEMA COLLECTION [ValidatedData]
GO

CREATE MESSAGE TYPE [WellFormedXMLSenderMessageType]
	VALIDATION = WELL_FORMED_XML
GO

CREATE MESSAGE TYPE [EmptySenderMessageType]
	VALIDATION = EMPTY
