IF EXISTS(SELECT 0 FROM SYS.ENDPOINTS WHERE NAME = 'SERVICE_BROKER_ENDPOINT')
BEGIN
	PRINT 'SERVICE_BROKER_ENDPOINT EXISTS'
	
	DROP ENDPOINT [SERVICE_BROKER_ENDPOINT]

END

CREATE ENDPOINT SERVICE_BROKER_ENDPOINT
STATE = STOPPED
AS TCP (
	LISTENER_PORT = 4022
)
FOR SERVICE_BROKER
	(AUTHENTICATION = CERTIFICATE [TRANSPORT_CERT_$(TRANSPORT_CERT_LOCAL_MACHINE_NAME)], ENCRYPTION = SUPPORTED)

PRINT 'SERVICE_BROKER_ENDPOINT CREATED'

FINISHED_ENDPOINT: