ARG MY_SA_PASSWORD=abcd1234!

FROM mcr.microsoft.com/mssql/server:2022-latest AS sql2022   

ARG MY_SA_PASSWORD

ENV ACCEPT_EULA=Y
ENV MSSQL_SA_PASSWORD=$MY_SA_PASSWORD

EXPOSE 1433 1433 4022 4022


VOLUME /var/opt/mssql/data
VOLUME /var/opt/mssql/service-broker
