/*
USE [master]
GO

CREATE DATABASE [ExampleKeyRepository]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ExampleKeyRepository', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\ExampleKeyRepository.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'ExampleKeyRepository_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\ExampleKeyRepository_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ExampleKeyRepository].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ExampleKeyRepository] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ExampleKeyRepository] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ExampleKeyRepository] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ExampleKeyRepository] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ExampleKeyRepository] SET ARITHABORT OFF 
GO

ALTER DATABASE [ExampleKeyRepository] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ExampleKeyRepository] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ExampleKeyRepository] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ExampleKeyRepository] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ExampleKeyRepository] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ExampleKeyRepository] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ExampleKeyRepository] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ExampleKeyRepository] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ExampleKeyRepository] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ExampleKeyRepository] SET  DISABLE_BROKER 
GO

ALTER DATABASE [ExampleKeyRepository] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ExampleKeyRepository] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ExampleKeyRepository] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ExampleKeyRepository] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ExampleKeyRepository] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ExampleKeyRepository] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ExampleKeyRepository] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ExampleKeyRepository] SET RECOVERY FULL 
GO

ALTER DATABASE [ExampleKeyRepository] SET  MULTI_USER 
GO

ALTER DATABASE [ExampleKeyRepository] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ExampleKeyRepository] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ExampleKeyRepository] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [ExampleKeyRepository] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [ExampleKeyRepository] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [ExampleKeyRepository] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [ExampleKeyRepository] SET QUERY_STORE = ON
GO

ALTER DATABASE [ExampleKeyRepository] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [ExampleKeyRepository] SET  READ_WRITE 
GO

*/

CREATE CERTIFICATE TRANSPORT_CERT_MACHINEA
    AUTHORIZATION [dbo]
    ENCRYPTION BY PASSWORD = '**(34ader#$lqQEUer13'
    WITH SUBJECT='Instance certificate for machine A for transport security';

CREATE CERTIFICATE TRANSPORT_CERT_MACHINEB
    AUTHORIZATION [dbo]
    ENCRYPTION BY PASSWORD = '**(34ader#$lqQEUer13'
    WITH SUBJECT='Instance certificate for machine B for transport security';

CREATE CERTIFICATE DIALOG_CERT_SERVICEBROKERA
    AUTHORIZATION [dbo]
    ENCRYPTION BY PASSWORD = '**(34ader#$lqQEUer13'
    WITH SUBJECT='Database certificate for machine A for dialog security';

CREATE CERTIFICATE DIALOG_CERT_SERVICEBROKERB
    AUTHORIZATION [dbo]
    ENCRYPTION BY PASSWORD = '**(34ader#$lqQEUer13'
    WITH SUBJECT='Database certificate for machine B for dialog security';

CREATE CERTIFICATE DIALOG_CERT_SERVICEBROKERC
    AUTHORIZATION [dbo]
    ENCRYPTION BY PASSWORD = '**(34ader#$lqQEUer13'
    WITH SUBJECT='Database certificate for machine C for dialog security';