--NOTE ABOUT ATTACHING SERVICE MASTER KEYS 
--IF A SERVICE MASTER KEY CHANGE HAPPENS,
--IT IS MY EXPERIENCE THAT THE MASTER KEY CHANGES TOO
--
--THIS SCENARIO WAS DURING A REMOTE MACHINE - CERTIFICATE AUTHENTICATION
CREATE MASTER KEY ENCRYPTION BY PASSWORD = 'Password123!@#'