IF EXISTS(SELECT 0 FROM SYS.CERTIFICATES WHERE NAME = 'TRANSPORT_CERT_MACHINE')
BEGIN
    PRINT 'CERTIFICATE TRANSPORT_CERT_MACHINE EXISTS'
	
	GOTO FINISHED_CREATE_CERTIFICATE_TRANSPORT_CERT_MACHINE
END

CREATE CERTIFICATE TRANSPORT_CERT_MACHINE
    AUTHORIZATION [dbo]
    FROM FILE  = N'$(CERTIFICATE_PATH)TRANSPORT_CERT_MACHINE.cer'
    WITH PRIVATE KEY (FILE = N'$(CERTIFICATE_PATH)TRANSPORT_CERT_MACHINE.pfx',
        DECRYPTION BY PASSWORD = N'$(CERTIFICATE_PASSWORD)'
    );

    PRINT 'CERTIFICATE TRANSPORT_CERT_MACHINE CREATED'

FINISHED_CREATE_CERTIFICATE_TRANSPORT_CERT_MACHINE: