IF EXISTS(SELECT 0 FROM SYS.SYSLOGINS WHERE NAME = 'SERVICE_BROKER_LOGIN')
BEGIN
	PRINT 'LOGIN SERVICE_BROKER_LOGIN EXISTS'
	
	GOTO FINISHED_CREATE_LOGIN_MACHINE_LOGIN
END

CREATE LOGIN SERVICE_BROKER_LOGIN
	FROM CERTIFICATE [TRANSPORT_CERT_$(TRANSPORT_CERT_LOCAL_MACHINE_NAME)];

PRINT 'LOGIN SERVICE_BROKER_LOGIN CREATED'

FINISHED_CREATE_LOGIN_MACHINE_LOGIN: