--NOTE ABOUT ATTACHING SERVICE MASTER KEYS 
--IF A SERVICE MASTER KEY CHANGE HAPPENS,
--IT IS MY EXPERIENCE THAT THE MASTER KEY CHANGES TOO
--
--THIS SCENARIO WAS DURING A REMOTE MACHINE - CERTIFICATE AUTHENTICATION
IF EXISTS(SELECT 0 FROM SYS.DATABASES WHERE NAME = N'$(DatabaseName)' and  is_master_key_encrypted_by_server = 0)
BEGIN
	PRINT '$(DatabaseName) MASTERKEY EXISTS'
	
	GOTO FINISHED_USER_MASTERKEY
END
	
CREATE MASTER KEY ENCRYPTION BY PASSWORD = '$(CERTIFICATE_PASSWORD)'

PRINT N'$(DatabaseName) MASTERKEY CREATED'

FINISHED_USER_MASTERKEY:


