PRINT 'REMOTE DIALOG CERT PATHS'

PRINT N'$(CERTIFICATE_PATH)\dialog\$(SERVICE_BROKER_REMOTE_DB_NAME)\public\$(TRANSPORT_CERT_REMOTE_MACHINE_NAME).$(SERVICE_BROKER_REMOTE_DB_NAME).cer'
IF EXISTS(SELECT 0 FROM SYS.CERTIFICATES WHERE NAME = N'DIALOG_$(SERVICE_BROKER_REMOTE_DB_NAME)')
BEGIN
    PRINT 'REMOTE DIALOG CERTIFICATE EXISTS'

	GOTO REMOTE_DIALOG_CERTIFICATE_COMPLETE
END

CREATE CERTIFICATE [Dialog_$(SERVICE_BROKER_REMOTE_DB_NAME)]
    AUTHORIZATION [User_$(SERVICE_BROKER_REMOTE_DB_NAME)]
    FROM FILE  = N'$(CERTIFICATE_PATH)\dialog\$(SERVICE_BROKER_REMOTE_DB_NAME)\public\$(TRANSPORT_CERT_REMOTE_MACHINE_NAME).$(SERVICE_BROKER_REMOTE_DB_NAME).cer';

    PRINT 'REMOTE DIALOG CERTIFICATE CREATED'

REMOTE_DIALOG_CERTIFICATE_COMPLETE:
GO
