--Private Key
IF NOT EXISTS(SELECT 0 FROM SYS.CERTIFICATES WHERE NAME = 'DIALOG_CERT_$(DatabaseName)')
BEGIN
	PRINT 'LOCAL CERTIFICATE EXISTS'
	
	GOTO FINISHED_LOCAL_CERTIFICATE
END

CREATE CERTIFICATE [DIALOG_CERT_$(DatabaseName)]
    AUTHORIZATION [dbo]
    FROM FILE  = '$(CERTIFICATE_PATH)DIALOG_CERT_$(DatabaseName).cer'
    WITH PRIVATE KEY (FILE = '$(CERTIFICATE_PATH)DIALOG_CERT_$(DatabaseName).pfx',
        DECRYPTION BY PASSWORD = '$(CERTIFICATE_PASSWORD)'
    );

PRINT 'LOCAL CERTIFICATE CREATED'

FINISHED_LOCAL_CERTIFICATE: