--Private Key
CREATE CERTIFICATE DIALOG_CERT_SERVICEBROKERB
    AUTHORIZATION [dbo]
    FROM FILE  = 'C:\Users\dbms-\source\repos\sql-server-service-broker\Certificates\DIALOG_CERT_SERVICEBROKERB.cer'
    WITH PRIVATE KEY (FILE = 'C:\Users\dbms-\source\repos\sql-server-service-broker\Certificates\DIALOG_CERT_SERVICEBROKERB.pfx',
        DECRYPTION BY PASSWORD = 'Password123!@#'
    );
GO

--Public Key Only

CREATE USER [User_SERVICEBROKERA]
WITHOUT LOGIN
GO

CREATE CERTIFICATE DIALOG_CERT_SERVICEBROKERA
    AUTHORIZATION [User_SERVICEBROKERA]
    FROM FILE  = 'C:\Users\dbms-\source\repos\sql-server-service-broker\Certificates\DIALOG_CERT_SERVICEBROKERA.cer'
GO

GRANT CONNECT TO [User_SERVICEBROKERA]

GO

GRANT SEND ON SERVICE::ServiceB_Out
    TO USER_SERVICEBROKERA
GO


/*
CREATE USER [User_SERVICEBROKERC]
WITHOUT LOGIN
GO

CREATE CERTIFICATE DIALOG_CERT_SERVICEBROKERC
    AUTHORIZATION [User_SERVICEBROKERC]
    FROM FILE  = 'C:\Users\dbms-\source\repos\sql-server-service-broker\Certificates\DIALOG_CERT_SERVICEBROKERC.cer'
GO

GRANT CONNECT TO [User_SERVICEBROKERC]

GO

GRANT SEND ON SERVICE::ServiceC_Out
    TO USER_SERVICEBROKERC
GO
*/