--Private Key
IF EXISTS(SELECT 0 FROM SYS.CERTIFICATES WHERE NAME = 'Dialog_$(DatabaseName)')
BEGIN
	PRINT 'LOCAL CERTIFICATE EXISTS'
	
	GOTO FINISHED_LOCAL_CERTIFICATE
END

CREATE CERTIFICATE [Dialog_$(DatabaseName)]
    AUTHORIZATION [dbo]
    FROM FILE  = '$(CERTIFICATE_PATH)\dialog\$(DatabaseName)\private\$(TRANSPORT_CERT_LOCAL_MACHINE_NAME).$(DatabaseName).cer'
    WITH PRIVATE KEY (FILE = '$(CERTIFICATE_PATH)\dialog\$(DatabaseName)\private\$(TRANSPORT_CERT_LOCAL_MACHINE_NAME).$(DatabaseName).pvk',
        DECRYPTION BY PASSWORD = '$(CERTIFICATE_PASSWORD)'
    );

PRINT 'LOCAL CERTIFICATE CREATED'

FINISHED_LOCAL_CERTIFICATE: