IF EXISTS(SELECT 0 FROM SYS.SYSUSERS WHERE NAME = N'User_$(SERVICE_BROKER_REMOTE_DB_NAME)')
BEGIN
	PRINT 'REMOTE USER EXISTS'

	GOTO REMOTE_USER_COMPLETE
END

CREATE USER [User_$(SERVICE_BROKER_REMOTE_DB_NAME)]
WITHOUT LOGIN

	PRINT 'REMOTE USER CREATED'

REMOTE_USER_COMPLETE:
