IF EXISTS(SELECT 0 FROM SYS.SYSLOGINS WHERE NAME = 'MACHINE_LOGIN')
BEGIN
	PRINT 'LOGIN MACHINE_LOGIN EXISTS'
	
	GOTO FINISHED_CREATE_LOGIN_MACHINE_LOGIN
END

CREATE LOGIN MACHINE_LOGIN
	FROM CERTIFICATE TRANSPORT_CERT_MACHINE;

PRINT 'LOGIN MACHINE_LOGIN CREATED'

FINISHED_CREATE_LOGIN_MACHINE_LOGIN: