IF EXISTS(SELECT 0 FROM SYS.SYSLOGINS WHERE NAME = 'MACHINELOGIN')
BEGIN
	PRINT 'LOGIN MACHINELOGIN EXISTS'
	
	GOTO FINISHED_CREATE_LOGIN_MACHINELOGIN
END

CREATE LOGIN MACHINE_LOGIN
	FROM CERTIFICATE TRANSPORT_CERT_MACHINE;

PRINT 'LOGIN MACHINELOGIN CREATED'

FINISHED_CREATE_LOGIN_MACHINELOGIN: