
PRINT 'CERT PATHS'
PRINT N'$(CERTIFICATE_PATH)\transport\$(TRANSPORT_CERT_LOCAL_MACHINE_NAME)\private\$(TRANSPORT_CERT_LOCAL_MACHINE_NAME).master.cer'
PRINT N'$(CERTIFICATE_PATH)\transport\$(TRANSPORT_CERT_LOCAL_MACHINE_NAME)\private\$(TRANSPORT_CERT_LOCAL_MACHINE_NAME).master.pvk'

IF EXISTS(SELECT 0 FROM SYS.CERTIFICATES WHERE NAME = 'TRANSPORT_CERT_$(TRANSPORT_CERT_LOCAL_MACHINE_NAME)')
BEGIN
    PRINT 'CERTIFICATE TRANSPORT_CERT_$(TRANSPORT_CERT_LOCAL_MACHINE_NAME) EXISTS'
	
	GOTO FINISHED_CREATE_CERTIFICATE_TRANSPORT_CERT_MACHINE
END


CREATE CERTIFICATE [TRANSPORT_CERT_$(TRANSPORT_CERT_LOCAL_MACHINE_NAME)]
    AUTHORIZATION [dbo]
    FROM FILE  = N'$(CERTIFICATE_PATH)\transport\$(TRANSPORT_CERT_LOCAL_MACHINE_NAME)\private\$(TRANSPORT_CERT_LOCAL_MACHINE_NAME).master.cer'
    WITH PRIVATE KEY (FILE = N'$(CERTIFICATE_PATH)\transport\$(TRANSPORT_CERT_LOCAL_MACHINE_NAME)\private\$(TRANSPORT_CERT_LOCAL_MACHINE_NAME).master.pvk',
        DECRYPTION BY PASSWORD = N'$(CERTIFICATE_PASSWORD)'
    );

PRINT 'CERTIFICATE TRANSPORT_CERT_$(TRANSPORT_CERT_LOCAL_MACHINE_NAME) CREATED'

FINISHED_CREATE_CERTIFICATE_TRANSPORT_CERT_MACHINE:
