USE ServiceBrokerB

CREATE REMOTE SERVICE BINDING ServiceBindingServiceA_Out 
	TO SERVICE 'SERVICEA_In'
	WITH USER = USER_SERVICEBROKERA
GO


CREATE REMOTE SERVICE BINDING ServiceBindingServiceC_Out
	TO SERVICE 'SERVICEC_In'
	WITH USER = USER_SERVICEBROKERC
GO
