USE ServiceBrokerB

CREATE REMOTE SERVICE BINDING ServiceBindingServiceA_In
	TO SERVICE 'ServiceA_Out'
	WITH USER = USER_SERVICEBROKERA
GO


CREATE REMOTE SERVICE BINDING ServiceBindingServiceC_In
	TO SERVICE 'ServiceC_Out'
	WITH USER = USER_SERVICEBROKERC
GO
