USE ServiceBrokerB

CREATE REMOTE SERVICE BINDING ServiceBindingServiceA_Out 
	TO SERVICE 'ServiceA_In'
	WITH USER = USER_SERVICEBROKERA
GO


CREATE REMOTE SERVICE BINDING ServiceBindingServiceC_Out
	TO SERVICE 'ServiceC_In'
	WITH USER = USER_SERVICEBROKERC
GO
