USE ServiceBrokerB

CREATE REMOTE SERVICE BINDING ServiceBindingServiceA 
	TO SERVICE 'SERVICEA'
	WITH USER = USER_SERVICEBROKERA
GO


CREATE REMOTE SERVICE BINDING ServiceBindingServiceC
	TO SERVICE 'SERVICEC'
	WITH USER = USER_SERVICEBROKERC
GO
