IF EXISTS(SELECT 0 FROM SYS.ENDPOINTS WHERE NAME = 'ENDPOINT_MACHINE')
BEGIN
	PRINT 'ENDPOINT_MACHINE EXISTS'
	GOTO FINISHED_ENDPOINT
END

CREATE ENDPOINT ENDPOINT_MACHINE
STATE = STOPPED
AS TCP (
	LISTENER_PORT = 4022
)
FOR SERVICE_BROKER
	(AUTHENTICATION = CERTIFICATE TRANSPORT_CERT_MACHINE, ENCRYPTION = SUPPORTED)

PRINT 'ENDPOINT_MACHINE CREATED'

FINISHED_ENDPOINT: