--Private Key
CREATE USER [User_SERVICEBROKERC]
WITHOUT LOGIN
GO

CREATE CERTIFICATE DIALOG_CERT_SERVICEBROKERC
    AUTHORIZATION [User_SERVICEBROKERC]
    FROM FILE  = 'C:\Users\dbms-\source\repos\sql-server-service-broker\Certificates\DIALOG_CERT_SERVICEBROKERC.cer'
    WITH PRIVATE KEY (FILE = 'C:\Users\dbms-\source\repos\sql-server-service-broker\Certificates\DIALOG_CERT_SERVICEBROKERC.pfx',
        DECRYPTION BY PASSWORD = 'Password123!@#'
    );
GO


GRANT SELECT TO USER_SERVICEBROKERC
GO

GRANT SUBSCRIBE QUERY NOTIFICATIONS TO [User_SERVICEBROKERC]
GO



--Public Key Only

CREATE USER [User_SERVICEBROKERA]
WITHOUT LOGIN
GO

CREATE CERTIFICATE DIALOG_CERT_SERVICEBROKERA
    AUTHORIZATION [User_SERVICEBROKERA]
    FROM FILE  = 'C:\Users\dbms-\source\repos\sql-server-service-broker\Certificates\DIALOG_CERT_SERVICEBROKERA.cer'
GO

GRANT CONNECT TO [User_SERVICEBROKERA]

GO

GRANT SEND ON SERVICE::ServiceC_In
    TO USER_SERVICEBROKERA
GO



