IF EXISTS(SELECT 0 FROM SYS.ROUTES WHERE NAME = 'Route$(REMOTE_SERVICE_NAME_)_In')
BEGIN
	DROP ROUTE [Route$(REMOTE_SERVICE_NAME_)_In]
END

CREATE ROUTE [Route$(REMOTE_SERVICE_NAME_)_In]
	AUTHORIZATION [USER_$(SERVICE_BROKER_REMOTE)]
	WITH
		SERVICE_NAME = N'$(REMOTE_SERVICE_NAME_)_In',
		ADDRESS = N'$(REMOTE_SERVICE_ADDRESS)',
		BROKER_INSTANCE = N'$(REMOTE_BROKER_ID)';