CREATE REMOTE SERVICE BINDING ServiceBindingServiceA 
	TO SERVICE 'SERVICEB'
	WITH USER = USER_SERVICEBROKERB
GO

CREATE REMOTE SERVICE BINDING ServiceBindingServiceC
	TO SERVICE 'SERVICEC'
	WITH USER = USER_SERVICEBROKERC
GO