IF EXISTS(SELECT 0 FROM SYS.REMOTE_SERVICE_BINDINGS WHERE NAME = N'ServiceBinding$(REMOTE_SERVICE_NAME_)_In')
BEGIN
	DROP REMOTE SERVICE BINDING [ServiceBinding$(REMOTE_SERVICE_NAME_)_In]
END

CREATE REMOTE SERVICE BINDING [ServiceBinding$(REMOTE_SERVICE_NAME_)_In]
	TO SERVICE N'$(REMOTE_SERVICE_NAME_)_Out'
	WITH USER = [User_$(SERVICE_BROKER_REMOTE)]
GO