CREATE REMOTE SERVICE BINDING ServiceBindingServiceB_In 
	TO SERVICE 'ServiceB_In'
	WITH USER = USER_SERVICEBROKERB
GO


CREATE REMOTE SERVICE BINDING ServiceBindingServiceC_In
	TO SERVICE 'ServiceC_In'
	WITH USER = USER_SERVICEBROKERC
GO
