CREATE REMOTE SERVICE BINDING ServiceBindingServiceB_In
	TO SERVICE 'SERVICEB_Out'
	WITH USER = User_SERVICEBROKERB
GO


CREATE REMOTE SERVICE BINDING ServiceBindingServiceC_In
	TO SERVICE 'SERVICEC_Out'
	WITH USER = USER_SERVICEBROKERC
GO
