CREATE REMOTE SERVICE BINDING ServiceBindingServiceB_Out
	TO SERVICE 'ServiceB_Out'
	WITH USER = User_SERVICEBROKERB
GO


CREATE REMOTE SERVICE BINDING ServiceBindingServiceC_Out
	TO SERVICE 'ServiceC_Out'
	WITH USER = USER_SERVICEBROKERC
GO
