USE ServiceBrokerA

CREATE REMOTE SERVICE BINDING ServiceBindingServiceB_Out 
	TO SERVICE 'SERVICEB_In'
	WITH USER = USER_SERVICEBROKERB
GO


CREATE REMOTE SERVICE BINDING ServiceBindingServiceC_Out
	TO SERVICE 'SERVICEC_In'
	WITH USER = USER_SERVICEBROKERC
GO
